name = "StreamingSampling"
uuid = "e1325ea1-13b9-452d-9115-4dbfefa12b3b"
authors = ["Emmanuel Lujan <eljn@mit.edu>"]
description = "StreamingSampling is a Julia-based proof-of-concept implementation of a streamed variant of maximum-entropy sampling (UPmaxentropy). It is designed to process large datasets stored on disk with minimal impact on RAM. The method first computes first-order inclusion probabilities using a DPP-based heuristic, and then feeds these probabilities into the classical UPmaxentropy algorithm to produce diverse samples."
version = "1.0.0-DEV"

[deps]
Determinantal = "2673d5e8-682c-11e9-2dfd-471b09c6c819"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Determinantal = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
